#! /bin/bash

sed 's:<td></td>::g' $1 | grep "<td>.*</td>" | awk 'NR%2==0' \
| tr '[:upper:]' '[:lower:]' | sed -e 's:<[^>]*>::g' -e 's:\x60:\x27:g' \
| tr -s ',[:blank:]' '\n' | tr -d '?' | sed -e 's:.*[^pkmnwlhaeiou\x27-].*::'\
 -e '/^$/d' | sort -u
