#!/bin/bash

export LC_ALL='en_US.utf8'
cd /usr/bin

list="$(ls /usr/bin | awk 'NR%101==004454718%101' | tr '\n' ' ')"
ldd $list | grep "0x" | sed -e 's:=.*$::' -e 's:(0.*)::' -e 's:[ \t]*::' | sort -u
